spring:
  application:
    name: JournalApp
  data:
    mongodb:
      uri: mongodb+srv://avinashmundolli:avinashmundolli@cluster0.iofkjup.mongodb.net/journaldb?retryWrites=true&w=majority
      database: journaldbs
      auto-index-creation: true

server:
  port: 8080
  servlet:
    context-path: /journal